### ISSUE TITLE
Add support for event management

### ISSUE THREAD

**Issue by arthurgustin** [Vinubaba/SANTC-API#18]
What I call event is an information that can occur on a daily basis and is associated to a kid. For instance, a teacher have a button to say "kid X : check in".

## Technical considerations ##

Events will be received by a message broker (pubsub) and processed by a new micro service called `event-manager`

The pubsub message could have this payload:
```
{
  "childId": "b189b600-b886-4118-affa-123dd406b821",
  "event": "E_CHECK_IN",
  "eventTime": "2017-11-05T13:15:30Z",
  "additionalInformations": {
    // informations specific to the event type
  }
}
```

Events to be treated are:

  * Check In `E_CHECK_IN`
  * Check Out `E_CHECK_OUT`
  * Mood  `E_MOOD`
    ->If mood is free text on the UI side, the event is `E_MOOD` and the `additionalInformations` will embed the free text content. If mood is a finite list, we could have several events type like `E_MOOD_HAPPY`, `E_MOOD_ANGRY`, `E_MOOD_GRUMPY`, etc...
  * Health `E_HEALTH`
  * Clothes `E_CLOTHES`
  * Supply `E_SUPPLY`
  * Notes `E_NOTES`
  * Meals `E_MEALS`

@Vinubaba I need your inputs regarding the event-specific informations, I wont start developing this right now, but I'd like to think about the architecture soon enough

**Comment by Vinubaba** [comment]
ok Thanks, Please see the sketch mockups and the wireframes because not all
events you have listed are accounted for. e.g. activities....
