### ISSUE TITLE
Notes vs Special instructions

### ISSUE THREAD

**Issue by arthurgustin** [Vinubaba/SANTC-API#6]
@Vinubaba I think notes and special instructions have "kinda" the same utility, what if we merged those 2 child attributes ?

**Comment by Vinubaba** [comment]
well, on the front end, one of them is really about special instructions
for the shown that is shown in highlights - things that are very important
but are more than a checkbox worth of things. and the notes is a running
list of notes that the admin or teacher can make. more of a progress notes
almost. so they serve 2 different purposes. would it be a problem?

Regards,

Vinu Singh
972-523-0729

**Comment by Vinubaba** [comment]
you can see the mockup for it too

Regards,

Vinu Singh
972-523-0729

**Comment by Vinubaba** [comment]
@arthurgustin what was the closure. was it added? not added?

**Comment by arthurgustin** [comment]
@Vinubaba yes since a while
